


# title: Website Name
# descripion: A website for uploading content
# age: 30

# # array
# tags:
#   - technology
#   - images
#   - creative

# indentation matters
# spaces

# objects

# address:
#   street: MG Road
#   city: Bengaluru
#   state: KA

# github actions
# env

# value: ${{ env.VALUE }}
# variable: ${{ github.VARIABLE_NAME }}



# Github

name: Github action ofr
on: 
  push: 
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print Node version
        run: node --version
      - name: Print NPM version
        run: npm --version
      - name: Print pwd
        run: pwd
      - name: Run eslint
        run: npx eslint .